---
- name: stunnel | install stunnel packages
  apt: name={{ item }} state=latest 
  with_items: "{{ stunnel_packages }}"

- name: stunnel | configure stunnels for relay to 465
  template: src=stunnel.conf.j2 dest=/etc/stunnel/stunnel.conf owner=root group=root mode=0600

- name: stunnel | enable stunnel
  lineinfile: path=/etc/default/stunnel4 regexp="^ENABLED=0" line="ENABLED=1"

- name: stunnel | create stunnel systemd unit
  copy: src=stunnel.service dest=/etc/systemd/system/stunnel.service owner=root group=root mode=0644

- name: stunnel | start and enable systemd unit
  systemd: daemon_reload=yes name=stunnel state=started enabled=yes
